export const GET_ALLDOGS = "GET_ALLDOGS";
export const GET_ALLTEMPERAMENTS = "GET_ALLTEMPERAMENTS";
export const GET_DOG_BY_NAME = 'GET_DOG_BY_NAME';
export const GET_DOG_DETAIL = 'GET_DOG_DETAIL';
export const POST_DOG ='POST_DOG';
export const FILTER_TEMPERAMENT = 'FILTER_TEMPERAMENT';
export const FILTER_API = 'FILTER_API';
export const FILTER_DB = 'FILTER_DB';
export const FILTER_ALL = 'FILTER_ALL';
export const ORDER_ASC = 'ORDER_ASC';
export const ORDER_DES = 'ORDER_DES';
export const ORDER_WEIGHT_MAX = 'ORDER_WEIGHT_MAX';
export const ORDER_WEIGHT_MIN = 'ORDER_WEIGHT_MIN'
export const RESET ='RESET';